### ISSUE TITLE
Crash after adding an URL that returns an empty document

### ISSUE THREAD

**Issue by gsauthof** [tughi/aggregator-android#1]
How to reproduce:

Select 'Add feed' and specify an URL that returns an empty document with HTTP 200.

Right now e.g. http://codemonkey.org.uk/ - cf.:

    $ curl -v  -L  http://codemonkey.org.uk/ 
    *   Trying 2400:cb00:2048:1::681c:753...
    * TCP_NODELAY set
    * Connected to codemonkey.org.uk (2400:cb00:2048:1::681c:753) port 80 (#0)
    > GET / HTTP/1.1
    > Host: codemonkey.org.uk
    > User-Agent: curl/7.51.0
    > Accept: */*
    > 
    < HTTP/1.1 200 OK
    < Date: Tue, 27 Dec 2016 20:45:23 GMT
    < Content-Type: text/html
    < Transfer-Encoding: chunked
    < Connection: keep-alive
    < Set-Cookie: __cfduid=d36eecfac6afd1ccb9ee4f0177c7f573c1482871523; expires=Wed, 27-Dec-17 20:45:23 GMT; path=/; domain=.codemonkey.org.uk; HttpOnly
    < Last-Modified: Fri, 09 Sep 2016 16:21:12 GMT
    < X-Content-Type-Options: nosniff
    < Server: cloudflare-nginx
    < CF-RAY: 317f9daaf6a66409-FRA
    < 
    * Curl_http_done: called premature == 0
    * Connection #0 to host codemonkey.org.uk left intact

Expected behaviour: display of an error message and no feed is added.

Actual behaviour: App crashes

Logcat output:

    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: At line 1, column 0: no element found
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: org.apache.harmony.xml.ExpatParser$ParseException: At line 1, column 0: no element found
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at org.apache.harmony.xml.ExpatParser.finish(ExpatParser.java:545)
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:485)
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at android.util.Xml.parse(Xml.java:71)
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at com.tughi.aggregator.feed.search.URLFeedSearchTask$AutoDiscoveryLinkHandler.processContent(URLFeedSearchTask.java:132)
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at com.tughi.aggregator.feed.search.URLFeedSearchTask$AutoDiscoveryLinkHandler.processContent(URLFeedSearchTask.java:53)
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at com.tughi.aggregator.http.CachedLinkHandler.processContent(CachedLinkHandler.java:33)
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at com.tughi.aggregator.http.LinkHandler.process(LinkHandler.java:121)
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at com.tughi.aggregator.feed.search.URLFeedSearchTask.search(URLFeedSearchTask.java:46)
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at com.tughi.aggregator.feed.search.SearchFeedTask.doInBackground(SearchFeedTask.java:43)
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at com.tughi.aggregator.feed.search.SearchFeedTask.doInBackground(SearchFeedTask.java:14)
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    12-27 21:48:00.880 29101 29472 D com.tughi.aggregator.feed.search.URLFeedSearchTask: 	at java.lang.Thread.run(Thread.java:761)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #6
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: Process: com.tughi.aggregator, PID: 29101
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:325)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: Caused by: java.lang.StringIndexOutOfBoundsException: length=8192; regionStart=0; regionLength=-1
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromChars(StringFactory.java:216)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at com.tughi.aggregator.feed.search.URLFeedSearchTask$AutoDiscoveryLinkHandler$SpyReader.getFirstReadResult(URLFeedSearchTask.java:211)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at com.tughi.aggregator.feed.search.URLFeedSearchTask$AutoDiscoveryLinkHandler.processContent(URLFeedSearchTask.java:139)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at com.tughi.aggregator.feed.search.URLFeedSearchTask$AutoDiscoveryLinkHandler.processContent(URLFeedSearchTask.java:53)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at com.tughi.aggregator.http.CachedLinkHandler.processContent(CachedLinkHandler.java:33)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at com.tughi.aggregator.http.LinkHandler.process(LinkHandler.java:121)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at com.tughi.aggregator.feed.search.URLFeedSearchTask.search(URLFeedSearchTask.java:46)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at com.tughi.aggregator.feed.search.SearchFeedTask.doInBackground(SearchFeedTask.java:43)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at com.tughi.aggregator.feed.search.SearchFeedTask.doInBackground(SearchFeedTask.java:14)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    12-27 21:48:00.882 29101 29472 E AndroidRuntime: 	... 4 more
    12-27 21:48:00.886  4889 26413 W ActivityManager:   Force finishing activity com.tughi.aggregator/.ui.SubscribeActivity

how reproducible: always

versions: current version from google play, android 7.1.1

**Comment by tughi** [comment]
This issue is not related to this open-source project.

**Comment by gsauthof** [comment]
Ok. Can you elaborate a little on how this open-source project relates to the com.tughi.aggregator app from the google play store?

Are they related, at all?

**Comment by tughi** [comment]
This is just a playground where I try new ideas.
