### ISSUE TITLE
Display article source

### ISSUE THREAD

**Issue by caesarsamsi** [tughi/aggregator-android#13]
I struggle to digest a feed that has a lot of articles in it. The list of titles is long and somewhat cryptic because they're just short titles.

For example I use the following feed to follow macos: https://news.google.com/rss/search?cf=all&hl=en-US&pz=1&q=macos&gl=US&ceid=US:en

When you open an article, the source is displayed after the title, so the data is there (at least in Google news).

It would be great if the list of articles in the feed could be grouped by the source.

I have been trying out PressReader and Feedly and wanting to find/enjoy an open source app.

**Comment by caesarsamsi** [comment]
Nevermind, the source is already displayed, I just didn't notice them. Grouping by source would still be nice though.

**Comment by tughi** [comment]
You could create tag rules for specific sources and see them later in the tags view.
