### ISSUE TITLE
Date feed not correct when sync feed

### ISSUE THREAD

**Issue by And96** [tughi/aggregator-android#14]
**Describe the bug**
Wrong dates. Same date for all articles of some websites. It shows hour of update insted of hour of the article.

**To Reproduce**
Add these URL:
https://tg24.sky.it/rss/tg24_cronaca.xml
https://www.wikihow.it/feed.rss

**Device (please complete the following information):**
 - Aggregator version: Preview-029
 - Device: Xiaomi Mi9
 - Android version: Android 10

**Screenshots**
![https://i.imgur.com/B9plscx.jpg](https://i.imgur.com/B9plscx.jpg)

**Comment by tughi** [comment]
First feed has invalid date format: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ftg24.sky.it%2Frss%2Ftg24_cronaca.xml

Second feed has no date for the included news items.

In both cases, as a fallback, the sync time is applied.
