### ISSUE TITLE
Horizontal switching between feeds/feed groups

### ISSUE THREAD

**Issue by sir-harlekin** [tughi/aggregator-android#16]
**Is your feature request related to a problem? Please describe.**
For feed or feed groups to be seperated, i really like a horizontal layout like in Palabre RSS (abandonware)

**Describe the solution you'd like**
Please see screenshot (explains it best)
https://cdn57.androidauthority.net/wp-content/uploads/2015/01/Palabre-710x426.jpg

**Comment by tughi** [comment]
Sorry, but such a layout requires the horizontal swipe gesture which is already used for something else. Besides this, I also cannot image it being very useful when you have lots of categories, or long category names.
