### ISSUE TITLE
Option to open article in default browser directly

### ISSUE THREAD

**Issue by jzav** [tughi/aggregator-android#20]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to open article in my default browser manually. I do this to be able to switch to article (reader) mode (in Firefox) and to bookmark page (when needed).

**Describe the solution you'd like**
Option to open articles directly in default browser. I would also like to be able to open article directly from main feed/source list. Without need to see "synapse" page. What about adding long tap for this?

**Describe alternatives you've considered**
Adding reader mode directly to Aggregator browser. But I suppose user would never be able to bookmark article to default browsers bookmarks.

**Comment by tughi** [comment]
It is interesting that nobody requested to bring back the click-on-icon feature from the old app.
I this what you want?
