### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by neodada** [tughi/aggregator-android#23]
Just asking.

**Comment by tomcat-xx** [comment]
I don't think so. I also sponsored developer on Patreon but account is not active anymore or at leas money could not be transferred.. 

At the moment for me the app is still working, even under Android 10. That can change in future but I did not find a better one so far.

**Comment by tughi** [comment]
Not dead.... lt is only hibernating... 😉
I use the app myself, but don't have much time to work on it for now.

**Comment by neodada** [comment]
Glad to see your reply.
