### ISSUE TITLE
Entry Rules help link broken

### ISSUE THREAD

**Issue by faircloughm** [tughi/aggregator-android#30]
clicking on Entry Rules help gives 404.

Page: http://tughi.github.io/aggregator-android/howto/rules.html DNE.

Found how to create rules from https://www.reddit.com/r/rss/comments/fecl5k/searching_android_rss_reader_app_that_filters/.

It works well - but I never would have worked it out without instructions.

**Comment by tughi** [comment]
The old app is not supported anymore

**Comment by anuraag488** [comment]
Will rules added in future?

**Comment by tughi** [comment]
The new app supports tag conditions.

Please check the examples on this [post](https://tughi.github.io/aggregator-android/2020/04/07/preview-027.html).

**Comment by anuraag488** [comment]
There should be 'not contains' condition present.

**Comment by tomcat-xx** [comment]
To do that you can exclude tags in settings for "My feed". So define tag with "contains" and then exclude it.

**Comment by anuraag488** [comment]
There should be 'not contains' condition present.

> To do that you can exclude tags in settings for "My feed". So define tag with "contains" and then exclude it.

I don't have any perticular exclude words. I want to exclude everything and include only "contains" some words. 
If i define include tags then other feeds will be filtered too.

**Comment by tughi** [comment]
Maybe the description in the "My feed settings" is not clear enough... "Included tags" is used to include only entries that have been tagged accordingly. Entries that don't have any of the selected "included tags" are left out.

The "excluded tags" is there to remove any "included tags" that have some other unwished tags.

**Comment by anuraag488** [comment]
I did understand correctly. Let me explain you through example.

I have FeedA and FeedB. I don't want any filtering on FeedA and want to include everything from FeedA. With FeedB i have created included tag. If i use included tags then FeedA will be left out. Correct?

I know i can make FeedA visible by assigning a included tag but what if i have hundreds of feeds which i need no filtering. I have to unnecessarily assign every feed included tag.

If there is "not contains" option available then i will create just 1 excluded tag for FeedB and everything from other feed will be shown.

**Comment by tughi** [comment]
You are correct that such a case is not supported. But I am worried that adding support for **not** will only create more problems...

Tags can have multiple rules (each being run separately)... and if you have one tag with rules like `title not contains "apples"` and  `title not contains "oranges"` you'll end up tagging all entries except the ones with both _apples_ and _oranges_.

**Comment by anuraag488** [comment]
> Tags can have multiple rules (each being run separately)... and if you have one tag with rules like `title not contains "apples"` and `title not contains "oranges"` you'll end up tagging all entries except the ones with both _apples_ and _oranges_.

I think i need exactly this for some feeds. Anyway it's upto you where it should be added or any other alternative.
