### ISSUE TITLE
"Show Read Entries" does not work

### ISSUE THREAD

**Issue by liar666** [tughi/aggregator-android#31]
**Describe the bug**

Unticking "Show Read Entries" does not work. See picture below: it is unticked but the 2 first entries (which are greyed, thus read) still appear.

**To Reproduce**

Just tick/untick the option several times, all the articles always displayed, whatever the status of "Show Read Entries" checkbox.

**Device (please complete the following information):**
 - Aggregator version: latest from play store (can't find any more info inside the app :{ )
 - Device: N10
 - Android version: 8.1

**Screenshots**

![Screenshot_20210223-090750](https://user-images.githubusercontent.com/3216927/108817232-da7ca980-75b7-11eb-9919-fa3bd72caa1f.png)

**Comment by tughi** [comment]
The Aggregator version you are using is not supported anymore.
