### ISSUE TITLE
"Contact author" email is dead link

### ISSUE THREAD

**Issue by liar666** [tughi/aggregator-android#32]
**Describe the bug**

Clicking the "Support > Contact (email the author)" creates an email to aggrgator-support@thugi.com which does not exists.

Would probably be better (for us and for you) to link to github issues' page.

**To Reproduce**

- Click the "Support > Contact (email the author)"
- send the email
- receive a notification from mailer daemon that email does not exist

**Device (please complete the following information):**
 - Aggregator version: latest from 
 - Device: N10
 - Android version: 8.1

**Comment by tughi** [comment]
The Aggregator version you are using is not supported anymore.
