### ISSUE TITLE
HELP!! Two URLs could not be connected, I don't know why.

### ISSUE THREAD

**Issue by telanxrays** [tughi/aggregator-android#34]
1. https://cn.nytimes.com/rss/
2. https://cn.wsj.com/zh-hant/rss

Press search button it shows "Cannot Open Connection".
It works fine on the Windows RSS client.
Is this a BUG?

**Comment by telanxrays** [comment]
> Strange, for me it is also working in Aggregator.

Really??? What's wrong with my Android? Thank you for your tip. I'll try it on another phone.

**Comment by tughi** [comment]
Both links work on my Android 11. 

You might have an older Android version or the certificates are not trusted by your phone.

**Comment by telanxrays** [comment]
@tughi Yes, you are right, thank you for your help. I got a new phone and it's worked fine.
