### ISSUE TITLE
Export ompl

### ISSUE THREAD

**Issue by shay3979** [tughi/aggregator-android#36]
I just love this app i was use the old one olso . But the new one i cant export my opml for beckup and more

**Comment by tomcat-xx** [comment]
You can find opml here: 
/Android/data/com.tughi.aggregator.next/files/feeds.opml
But it just contains feeds, not tags.

**Comment by shay3979** [comment]
Ty verry much with tags its ok .. 
Have a nice day and hope for more update cos its the best rss i use so far  with few more its will be better from all paid and free rss .
i and i check almost all i use the old one before

**Comment by pc00per** [comment]
@shay3979 You can close this issue btw
