### ISSUE TITLE
Bug: Failed to parse XML

### ISSUE THREAD

**Issue by DemonInTheCloset** [tughi/aggregator-android#39]
**Describe the bug**
Can't parse the XML of [this](https://www.elmostrador.cl/feed/) feed.

I'm guessing it has to do with the header being like this:
```xml
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
     xmlns:content="http://purl.org/rss/1.0/modules/content/"
     xmlns:wfw="http://wellformedweb.org/CommentAPI/"
     xmlns:dc="http://purl.org/dc/elements/1.1/"
     xmlns:atom="http://www.w3.org/2005/Atom"
     xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
     xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
     xmlns:media="http://search.yahoo.com/mrss/"      >
```

**To Reproduce**
- Add https://www.elmostrador.cl/feed/ and set language to es
- Refresh

**Device (please complete the following information):**
 - Aggregator version: Preview-030
 - Device: Samsung S9
 - Android version: Android 10

**Screenshots**
![aggregator error message](https://user-images.githubusercontent.com/41545008/144760382-2bb00714-b2ed-40ed-858c-fa64eb04560e.png)

**Comment by tughi** [comment]
The screenshot is taken from the old app.

I couldn't reproduce the issue with the new app.
