### ISSUE TITLE
Can't import opml with double quotation marks in a feed title

### ISSUE THREAD

**Issue by Kzer-Za** [tughi/aggregator-android#44]
**Describe the bug**
The parser breaks at the double quotation marks and none of the feeds from the opml file is imported.

**To Reproduce**
1. Create an opml file with a line that contains double quotation marks. For example, this line:
<outline title=""Элементы": новости науки" text=""Элементы": новости науки" description=""Элементы": новости науки" type="rss" xmlUrl="http://elementy.ru/rss/news"/>
(I have not edited the title of this feed, so I assume this title is what is automatically fetched when you subscribe to this RSS).
2. Try to import this file.

**Device (please complete the following information):**
 - Aggregator version: 2.22.000
 - Device: KingKong Mini2
 - Android version: Android 9

**Comment by tughi** [comment]
You have to properly escape those quotes, otherwise your XML is invalid.
