### ISSUE TITLE
[Bug] App launch isn't always recognized, preventing feed update on application launch

### ISSUE THREAD

**Issue by RequestPrivacy** [tughi/aggregator-android#76]
**Describe the bug**
After quitting the app and reopening the feeds aren't updated even though update mode is set "Auto update: on app launch"

**To Reproduce**
- Go to Settings -> System -> Gestures
- Enable "Gesture navigation"
- Open Aggregator and go to "Feeds"
- Click on a Feed -> Settings -> Update mode. 
- Set "On application launch" and save

- Bring up task manager (swipe from bottom up but hold, don't release finger)
- Kill Aggregator
- Re-open Aggregator
- Go to Feeds and click on previously edited feed
- Notice new updated feed time.

NOW
- Quit app via right swipe from left window border, without killing the app via task manager
- Wait couple minutes
- Start app again
- Go to Feeds and click on previously edited feed
- Notice OLD update time, no refresh!

**Reasoning**
I am picky about how often and at what times my device connects to the internet. I want to be in control. Therefore I tend to limit background updates/refreshes. "Update on app launch" seems a good fit for me. Yet I'm under the impression that Aggregator can't differentiate to well between a short therm switch to/from the app and a "new" app launch unless you really kill the app manually via the task manager?

It would really help to have a manual way to update e.g. via a pull down action.

BTW, great app, many thanks for your work!

**Device (please complete the following information):**
 - Aggregator version: Preview-032]
 - Device: Google Pixel 4a
 - Android version: Android 13

**Screenshots**
Not applicable

**Comment by tughi** [comment]
Hmmm... I can confirm that using the new gestures, Android doesn't finish the MainActivity anymore when you use the "back gesture". This is the reason why app-launches aren't recongnized anymore untill Android kills itself the app.

As a workaround the MainActivity has to use an OnBackPressedDispatcher to recognize the user's intention to leave the app and prepare for a new app-launch.

**Comment by RequestPrivacy** [comment]
Thanks for fixing. Looking forward for F-Droid providing the new version in their repos...
