### ISSUE TITLE
Aggregator not able to read reddit rss channels

### ISSUE THREAD

**Issue by vbresan** [tughi/aggregator-android#87]
Reddit has made changes in their RSS feed. In particular (I believe) content tag now has type="html" attribute. Aggregator 2.22 is reporting "Fail message: Failed to parse feed content: html". See the sceenshot.

First I thought that the latest version, Preview:033 knows how to handle the issue, so I have installed that one too. I was not able to add reddit RSS feed to it. The error message is saying: No feeds found. See the sceenshot.

Try to add any reddit RSS feed, for example:
https://www.reddit.com/r/androidapps.rss

 - Aggregator version: 2.22, Preview-033
 - Xiaomi Redmi Note 2
 - Android version: 5.0

Screenshots
![2023-08-13 15 55 51](https://github.com/tughi/aggregator-android/assets/288855/94603507-c3d9-4d2f-a762-526e06f5e111)
![2023-08-13 15 57 37](https://github.com/tughi/aggregator-android/assets/288855/6c4bb953-d59f-45cf-9647-4bf9fe6bd55e)

**Comment by tughi** [comment]
It is not a bug if Reddit doesn't provide RSS feeds anymore.
