### ISSUE TITLE
Godot feed only description fetched

### ISSUE THREAD

**Issue by myryk31415** [tughi/aggregator-android#94]
**Describe the bug**
Only Headline and some sort of description get fetched from godotengine.org, not the entire article.

E.g:
>Looking back at a month of game jams, we curated a list of ten events that you might or might not have heard of before.

And thats it, no list. Downloaded another rss reader to check its not an issue on the website, but there the whole article gets fetched,.

**To Reproduce**
https://godotengine.org/rss.xml
Add feed, refresh. Look at the entries.

**Device (please complete the following information):**
 - Aggregator version: Preview:33
 - Device: Redmi Note 7
 - Android version: Android 11

**Screenshots**
If description unclear i can provide some.

**Comment by myryk31415** [comment]
gimp.org has two feeds, rss and atom, rss has the same issue, atom works as expected

**Comment by tughi** [comment]
This is not a bug. The provided feed doesn't provide whole articles.

**Comment by myryk31415** [comment]
Oh okay. Weird that it works in Feeder. whatever. Have a great day
