### ISSUE TITLE
Confusing loading state in Battery Saver

### ISSUE THREAD

**Issue by graciouselectric** [tughi/aggregator-android#95]
**Describe the bug**
Dear developer,

I noticed that, when I enable Battery Saver on Android 8.1, the indeterminate `ProgressBar`s in the app are not properly shown. This is a known problem in Android API level <28, see e.g. [this StackOverflow question](https://stackoverflow.com/questions/35221706/progressbar-disappears-in-battery-saver-mode-android-5-x). Battery Saver disables animations, also on progress bars on these versions. This is quite confusing because the loading state is not properly represented. It is fixed in later Android versions, where progress bars do appear and animate.

Looking at the code, indeterminate progress bars are created here, among other places:

```
className='com.tughi.aggregator.activities.backup.BackupActivity$onCreate$6', lineNumber=112
```

To fix this issue, one can check [ValueAnimator.areAnimatorsEnabled()](https://developer.android.com/reference/android/animation/ValueAnimator) and provide a different UI element, such as a text label, when animations are disabled.

**To Reproduce**
- Turn on Battery Saver
- Add a feed
**Device (please complete the following information):**
 - Aggregator version: Preview-33
 - Android version: Android 8.1
**Screenshots**

https://github.com/tughi/aggregator-android/assets/165037835/fc86d18b-65dc-4b0e-a2a7-b182f404b7ff

**Comment by tughi** [comment]
Thanks for investigating this issue.

From what I see, the standard ProgressBar already handles the case by displaying a static image instead.

Therefore I consider it to be a minor issue for which it is not worth implementing a work-around.
